### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by chrisvander** [filipesilva/paulgraham-rss#1]
Hey, any way you can add dates to this? My RSS Reader is just throwing them all in as though it’s the same date.

**Comment by filipesilva** [comment]
I'm not too sure what's the good way to get the dates from tbh.

I see a date inside the articles themselves (e.g. `April 2016` in https://paulgraham.com/pgh.html). I guess I can fetch each article and try to parse that.

Do you have any better approach than that?

**Comment by chrisvander** [comment]
As far as I can tell that's the only reference to the date on the page. Clojure can use a `SimpleDateFormat` from Java 8, right?

```
(java.text.SimpleDateFormat. "MMMM YYYY")
    (.parse
        (...))
```

**Comment by filipesilva** [comment]
It's definitively parseable, but will require pulling the articles in addition to the index. That's not too bad once a day. If it becomes a problem then probably I'll have to move from the current stateless model to a stateful one (only get new ones articles).

**Comment by chrisvander** [comment]
It isn't too many articles so yes, agreed, that may work fine. How fast can Paul write anyway? He's quite concise.

**Comment by filipesilva** [comment]
Should have dates now. Let me know if there's any trouble.
